# Generated by Django 5.0.4 on 2024-04-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedmusic',
            name='release_date',
        ),
    ]
