# Generated by Django 5.0.4 on 2024-04-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_recommendedmusic_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedmusic',
            name='popularity',
        ),
    ]
